theme: jekyll-theme-minimal
title: Emily Zhou's Portfolio
description: Hi there! My name is Emily. I graduated from Middlebury College with a major in Geography and minors in Japanese and Computer Science. I am currently a first-year City Planning student at UPenn's Weitzman School of Design. 

