theme: jekyll-theme-minimal
title: Emily Zhou's Portfolio
description: Hi there! My name is Emily and I am a senior student at Middlebury College majoring in Geography and double minoring in Computer Science and Japanese Studies. This page documents GIS analyses, data visualization, cartographic and research works that I have done at Middlebury.  
