theme: jekyll-theme-minimal
title: Emily Zhou's Portfolio
description: >
Hi there! My name is Emily and I graduated from Middlebury College with a major in Geography and minors in Japanese and Computer Science.   
<br><br>
I am currently a City Planning student at University of Pennsylvania's Weitzman School of Design, concentrating in Smart Cities and Urban Spatial Analytics.  

